# Site settings
title: Sergine Desjardins
email: serginedesjardins@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site personel de Sergine Desjardins
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://serginedesjardins.github.io/" # the base hostname & protocol for your site
twitter_username: sergine54
github_username: serginedesjardins

# Build settings
markdown: kramdown
